from __future__ import annotations

from typing import List
from app.schemas.analysis import EvaluationSignals, RetrievedKnowledge, RiskScore, VulnerabilityFinding


class ReportWriterAgent:
    name = "Report Writer Agent"

    def write(
        self,
        title: str,
        summary: str,
        findings: List[VulnerabilityFinding],
        risk: RiskScore,
        attack_path: List[str],
        defenses: List[str],
        executive_actions: List[str],
        retrieved_knowledge: List[RetrievedKnowledge],
        evaluation: EvaluationSignals,
    ) -> str:
        lines: List[str] = []
        lines.append(f"# SecureAI Sentinel Security Analysis Report: {title}\n")
        lines.append("## Executive Summary")
        lines.append(summary)
        lines.append("")
        lines.append("## Risk Rating")
        lines.append(f"- **Severity:** {risk.severity}")
        lines.append(f"- **Score:** {risk.score}/100")
        lines.append(f"- **Priority:** {risk.priority}")
        lines.append(f"- **Recommended SLA:** {risk.remediation_sla}")
        lines.append(f"- **Rationale:** {risk.rationale}")
        if risk.drivers:
            lines.append("- **Risk Drivers:** " + "; ".join(risk.drivers))
        lines.append("")
        lines.append("## CVSS-Style Risk Vector")
        lines.append(f"- **Attack Vector:** {risk.vector.attack_vector}")
        lines.append(f"- **Attack Complexity:** {risk.vector.attack_complexity}")
        lines.append(f"- **Privileges Required:** {risk.vector.privileges_required}")
        lines.append(f"- **User Interaction:** {risk.vector.user_interaction}")
        lines.append(f"- **Confidentiality Impact:** {risk.vector.confidentiality}")
        lines.append(f"- **Integrity Impact:** {risk.vector.integrity}")
        lines.append(f"- **Availability Impact:** {risk.vector.availability}")
        lines.append(f"- **Exploitability:** {risk.vector.exploitability}")
        lines.append(f"- **Business Impact:** {risk.vector.business_impact}")
        lines.append("")
        lines.append("## Key Findings")
        for idx, finding in enumerate(findings, 1):
            lines.append(f"### {idx}. {finding.category}")
            lines.append(f"- **Status:** {finding.status}")
            lines.append(f"- **Severity hint:** {finding.severity_hint}")
            if finding.cwe:
                lines.append(f"- **CWE:** {finding.cwe}")
            if finding.owasp:
                lines.append(f"- **OWASP:** {finding.owasp}")
            lines.append(f"- **Confidence:** {finding.confidence:.2f}")
            lines.append(f"- **Explanation:** {finding.explanation}")
            lines.append(f"- **Matched Evidence:** {', '.join(finding.evidence) if finding.evidence else 'No direct keyword evidence; review required.'}")
            if finding.evidence_refs:
                lines.append("- **Evidence References:**")
                for ref in finding.evidence_refs[:5]:
                    lines.append(f"  - {ref.source} / {ref.locator}: {ref.excerpt}")
            lines.append("")
        lines.append("## Potential Attack Path")
        for idx, step in enumerate(attack_path, 1):
            lines.append(f"{idx}. {step}")
        lines.append("")
        lines.append("## Defense Recommendations")
        for rec in defenses:
            lines.append(f"- {rec}")
        lines.append("")
        lines.append("## Executive Action Plan")
        for action in executive_actions:
            lines.append(f"- {action}")
        lines.append("")
        lines.append("## Retrieved Knowledge Context")
        for item in retrieved_knowledge:
            lines.append(f"- **{item.source} / {item.section}** (score {item.score:.2f}): {item.content}")
        lines.append("")
        lines.append("## Evaluation Signals")
        lines.append(f"- **Retrieval coverage:** {evaluation.retrieval_coverage:.2f}")
        lines.append(f"- **Hallucination guardrail:** {evaluation.hallucination_guardrail}")
        lines.append(f"- **Consistency note:** {evaluation.consistency_note}")
        lines.append(f"- **Overall confidence:** {evaluation.confidence:.2f}")
        lines.append("")
        lines.append("## Remediation Workflow")
        lines.append("1. Confirm or reject each finding in the analyst review workflow.")
        lines.append("2. Create remediation tickets for confirmed findings.")
        lines.append("3. Retest after fixes and attach validation evidence.")
        lines.append("4. Mark the finding as Fixed, Accepted Risk, False Positive, or Needs Review.")
        lines.append("")
        lines.append("## Limitations")
        lines.append("This report is generated by an AI-assisted security triage prototype. Findings should be validated by a qualified analyst before production decisions.")
        return "\n".join(lines)
